### PR TITLE
[TASK] Align with new TYPO3 documentation standards

### PR DESCRIPTION
**Pull request by alexander-nitsche**
Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/182

### CODE REVIEW

**Comment by alexander-nitsche** [comment]
What is missing: 
(1) Registering this documentation for rendering and publishing at docs.typo3.org with the [webhook](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingDocForExtension/Webhook.html#github).
(2) Remove any documentation URL from the "External manual" field of the TER extension page configuration at https://extensions.typo3.org as the documentation at docs.typo3.org is detected automatically and a specific URL is error-prone.

**Comment by alexander-nitsche** [comment]
How it looks:
Screen Shot 2022-04-04 at 18 37 36

**Comment by alexander-nitsche** [comment]
Added new commit regarding additional sources (TER, repository and docs.typo3.org) in composer.json.

Relates: TYPO3-Documentation/T3DocTeam#185

**Comment by ohader** [comment]
TER foo done

**Pull request merged**
